# Q11. Answer

In [6]:
# given Average weight =200
# given Standard deviation = 30

In [7]:
from scipy import stats
import numpy as np
import pandas as pd

In [8]:
ci_1=np.round(stats.norm.interval(0.94,200,30),3)
ci_1

array([143.576, 256.424])

In [9]:
ci_2=np.round(stats.norm.interval(0.98,200,30),3)
ci_2

array([130.21, 269.79])

In [10]:
ci_3=np.round(stats.norm.interval(0.96,200,30),3)
ci_3

array([138.388, 261.612])

# Q12. Answer

In [11]:
x=[34,36,36,38,38,39,39,40,40,41,41,41,41,42,42,45,49,56]

In [13]:
np.mean(x)

41.0

In [14]:
np.median(x)

40.5

In [15]:
np.var(x)

24.11111111111111

In [17]:
np.std(x)

4.910306620885412

In [20]:
np.sqrt(np.var(x))

4.910306620885412