In [45]:
import numpy as np
import seaborn as sns
import pandas as pd

In [4]:
data= sns.load_dataset("iris")

In [5]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
a=data.iloc[:,:-1]

In [19]:
a

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [20]:
a_t=a.transpose()

In [21]:
a_t

0    1    2    3    4    5    6    7    8    9    ...  140  141  \
sepal_length  5.1  4.9  4.7  4.6  5.0  5.4  4.6  5.0  4.4  4.9  ...  6.7  6.9   
sepal_width   3.5  3.0  3.2  3.1  3.6  3.9  3.4  3.4  2.9  3.1  ...  3.1  3.1   
petal_length  1.4  1.4  1.3  1.5  1.4  1.7  1.4  1.5  1.4  1.5  ...  5.6  5.1   
petal_width   0.2  0.2  0.2  0.2  0.2  0.4  0.3  0.2  0.2  0.1  ...  2.4  2.3   

              142  143  144  145  146  147  148  149  
sepal_length  5.8  6.8  6.7  6.7  6.3  6.5  6.2  5.9  
sepal_width   2.7  3.2  3.3  3.0  2.5  3.0  3.4  3.0  
petal_length  5.1  5.9  5.7  5.2  5.0  5.2  5.4  5.1  
petal_width   1.9  2.3  2.5  2.3  1.9  2.0  2.3  1.8  

[4 rows x 150 columns]

In [24]:
result = np.dot(a_t,a)

In [25]:
result

array([[5223.85, 2673.43, 3483.76, 1128.14],
       [2673.43, 1430.4 , 1674.3 ,  531.89],
       [3483.76, 1674.3 , 2582.71,  869.11],
       [1128.14,  531.89,  869.11,  302.33]])

In [30]:
eigh_value,eigh_vector=np.linalg.eigh(result)

In [31]:
eigh_value

array([3.55257020e+00, 1.19780429e+01, 3.15454317e+02, 9.20830507e+03])

In [32]:
eigh_vector

array([[ 0.32081425,  0.50215472,  0.2841749 , -0.75110816],
       [-0.31725607, -0.67524332,  0.5467445 , -0.38008617],
       [-0.48074507, -0.05916621, -0.70866455, -0.51300886],
       [ 0.75187165, -0.53701625, -0.34367081, -0.16790754]])

In [48]:
Z=np.dot(a,eigh_vector)
z=pd.DataFrame(Z)
z

0         1         2         3
0    0.003088  0.007402  2.302033 -5.912747
1    0.097553  0.244592  1.971826 -5.572482
2    0.018013  0.015029  2.095206 -5.446977
3   -0.078492  0.020505  1.870382 -5.436459
4   -0.060719 -0.110338  2.328290 -5.875645
..        ...       ...       ...       ...
145  0.427118 -0.204095 -0.931293 -9.226517
146  0.252820  0.159305 -1.039134 -8.566265
147  0.137393 -0.143421 -0.885027 -9.025923
148  0.043659 -0.737103 -0.996416 -9.105599
149 -0.157395 -0.331394 -0.915931 -8.490375

[150 rows x 4 columns]

In [63]:
z1=z[0]

In [64]:
z1

0      0.003088
1      0.097553
2      0.018013
3     -0.078492
4     -0.060719
         ...   
145    0.427118
146    0.252820
147    0.137393
148    0.043659
149   -0.157395
Name: 0, Length: 150, dtype: float64

In [62]:
z2=z[1]
z2

0      0.007402
1      0.244592
2      0.015029
3      0.020505
4     -0.110338
         ...   
145   -0.204095
146    0.159305
147   -0.143421
148   -0.737103
149   -0.331394
Name: 1, Length: 150, dtype: float64

In [66]:
z3=z[2]
z3

0      2.302033
1      1.971826
2      2.095206
3      1.870382
4      2.328290
         ...   
145   -0.931293
146   -1.039134
147   -0.885027
148   -0.996416
149   -0.915931
Name: 2, Length: 150, dtype: float64

In [67]:
z4=z[3]
z4

0     -5.912747
1     -5.572482
2     -5.446977
3     -5.436459
4     -5.875645
         ...   
145   -9.226517
146   -8.566265
147   -9.025923
148   -9.105599
149   -8.490375
Name: 3, Length: 150, dtype: float64

In [74]:
z1,z2,z3,z4

(0      0.003088
 1      0.097553
 2      0.018013
 3     -0.078492
 4     -0.060719
          ...   
 145    0.427118
 146    0.252820
 147    0.137393
 148    0.043659
 149   -0.157395
 Name: 0, Length: 150, dtype: float64,
 0      0.007402
 1      0.244592
 2      0.015029
 3      0.020505
 4     -0.110338
          ...   
 145   -0.204095
 146    0.159305
 147   -0.143421
 148   -0.737103
 149   -0.331394
 Name: 1, Length: 150, dtype: float64,
 0      2.302033
 1      1.971826
 2      2.095206
 3      1.870382
 4      2.328290
          ...   
 145   -0.931293
 146   -1.039134
 147   -0.885027
 148   -0.996416
 149   -0.915931
 Name: 2, Length: 150, dtype: float64,
 0     -5.912747
 1     -5.572482
 2     -5.446977
 3     -5.436459
 4     -5.875645
          ...   
 145   -9.226517
 146   -8.566265
 147   -9.025923
 148   -9.105599
 149   -8.490375
 Name: 3, Length: 150, dtype: float64)

In [77]:
pd.DataFrame({"Z1":z1,"Z2":z2,"Z3":z3,"Z4":z4})

Z1        Z2        Z3        Z4
0    0.003088  0.007402  2.302033 -5.912747
1    0.097553  0.244592  1.971826 -5.572482
2    0.018013  0.015029  2.095206 -5.446977
3   -0.078492  0.020505  1.870382 -5.436459
4   -0.060719 -0.110338  2.328290 -5.875645
..        ...       ...       ...       ...
145  0.427118 -0.204095 -0.931293 -9.226517
146  0.252820  0.159305 -1.039134 -8.566265
147  0.137393 -0.143421 -0.885027 -9.025923
148  0.043659 -0.737103 -0.996416 -9.105599
149 -0.157395 -0.331394 -0.915931 -8.490375

[150 rows x 4 columns]

In [78]:
eigh_value

array([3.55257020e+00, 1.19780429e+01, 3.15454317e+02, 9.20830507e+03])

In [83]:
sum=eigh_value[0]+eigh_value[2]+eigh_value[3]+eigh_value[3]
sum

18735.617027409935

In [84]:
eigh_value[0]/sum

0.0001896158636400052